### ISSUE TITLE
Should use closed-form fibonacci function

### ISSUE THREAD

**Issue by isaacs** [glenjamin/node-fib#1]
It would be much more performant to calculate the fibonacci number like so:

``` javascript
function fib (n) {
  var a=1
    , b=0
  while (0 > n--) {
    var c = b
    b = b + a
    a = c
  }
  return b
}
```

Perhaps it might make sense to add this as a separate endpoint?

**Comment by glenjamin** [comment]
I've now implemented this as in #7 - which keeps the recursive step - thus making it easier to work in releasing the loop periodically.

**Comment by jkff** [comment]
Actually there's a logarithmic-time algorithm, guys... Google it.

**Comment by isaacs** [comment]
@jkff GIST OR GTFO.

**Comment by bcjordan** [comment]
```
while (0 > n--) {
```

Should be < instead of >.

**Comment by isaacs** [comment]
True that.  need tdd on this thing.

**Comment by jkff** [comment]
http://www.csse.monash.edu.au/~lloyd/tildeProgLang/C/Recn/fibLog.c

**Comment by leonth** [comment]
Seriously guys, it's O(1).

```
var PHI = (1 + Math.sqrt(5)) / 2;
function fib(n) {
    return Math.round(Math.pow(PHI, n) / Math.sqrt(5));
}
```

**Comment by glenjamin** [comment]
See issue #4

On 4 Oct 2011, at 18:34, leonth
reply@reply.github.com
wrote:

**Comment by jkff** [comment]
@leonth For which range of inputs does it give an exact answer?

**Comment by leonth** [comment]
Okay, my bad...

**Comment by ghost** [comment]
@leonth I'm not sure about this, but I don't think that Math.pow is O(1). The compiler could do some extremely aggressive optimization by precomputing various powers of the known base, but this is a bit much to expect. I'd call it O(lg(n))

**Comment by bdonlan** [comment]
O(lg(n)) at a minimum is required for exact output - as you're producing an output string of O(n) bits. I don't know offhand what the complexity of exact (arbitrary-precision with irrationals) pow/round would be - probably something quite large; certainly larger than the O(n lg n) solution adding arbitrary-precision integers. However, if you're using doubles (possibly a bad idea; after n> 50something you'll start rounding) it will be O(1); it'll be essentially doing modular exponentiation with a fixed modulus.

**Comment by ghost** [comment]
@bdonlan How do you do modular exponentiation in constant time? Exponentiation by squaring is lg(n)

**Comment by bdonlan** [comment]
@bpgordon doubles have fixed maximum range; therefore n is a constant, so O(1). At the silicon level we're talking about a fixed upper bound on how many cycles any operation with a double will take. Hence my comments on exact output; doubles won't work for very high parameters.
