### ISSUE TITLE
Memoize results in an LRU cache

### ISSUE THREAD

**Issue by isaacs** [glenjamin/node-fib#2]
For optimum performance, the server should use node-lru-cache to memoize the results of each calculation in a lru cache.  (`npm install lru-cache` is a pretty well tested O(1) implementation.)

**Comment by glenjamin** [comment]
This would have been worth doing to avoid hitting the memory limit (although I suspect the stacks used more memory than the cache).

However, too many people got sidetracked by the memoisation instead of the important bit (nextTick). Thus I've removed the cache entirely.
