### ISSUE TITLE
Cannot calculate 1,000,000th Fibonacci number

### ISSUE THREAD

**Issue by tarcieri** [glenjamin/node-fib#3]
This crashes node-fib:

```
$ time curl localhost:3000/1000000
curl: (52) Empty reply from server

real    1m0.392s
user 0m0.006s
sys 0m0.004s
```

It appears it ran out of memory:

```
$ node app.js 
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

**Comment by rbranson** [comment]
Looks to be a potential DoS vector.

**Comment by glenjamin** [comment]
I shall alert those intending to use this in production that there may be a security issue :)

**Comment by glenjamin** [comment]
While the new algorithm does support n=1000000, JavaScript's native number type does not.

**Comment by Incognito** [comment]
Woah woah woah, why are you closing this? Just use bignum. http://jsfromhell.com/classes/bignumber

**Comment by glenjamin** [comment]
I've already spent far more time on this than I intended, pull requests for bignum support are welcome.

Had a cursory glance over that bignum library, it looks horrible!
