### ISSUE TITLE
Improve ten-fold by knowing math

### ISSUE THREAD

**Issue by clyfe** [glenjamin/node-fib#4]
O(log n)

```
phi = (1 + Math.sqrt(5)) / 2
fibonacci = (n) -> Math.floor(Math.pow(phi, n) / Math.sqrt(5) + 1/2)
fibonacci(10) # => 55
```

**Comment by clyfe** [comment]
No way to delete this is there :D ?
On a second thought I think it might limit the concurrency level, yet improve the response time and use less memory ...

**Comment by glenjamin** [comment]
As discussed here: http://news.ycombinator.com/item?id=3067508

This approach suffers from floating point precision problems (as would the additive approach at high values, i'd expect).

Interesting algorithm though, not something I'd come across before.
