### ISSUE TITLE
fewer dependencies

### ISSUE THREAD

**Issue by ghost** [glenjamin/node-fib#7]
Perhaps some code like this with fewer dependencies (and less memory used) could work.
For 1000000 it returns Infinity, for 1000 it returns 2.686381002448534e+208 in 0.071s

``` javascript
function fibonacci(nfib, cb) {
  function fib(n1, n2, n, cb) {
    if(n > nfib) return cb(n2)
    process.nextTick(function() { fib(n2, n1 + n2, n + 1, cb) })
  }
  switch(nfib) {
    case 1: cb(0); break
    case 2: cb(1); break
    default: fib(0, 1, 3, cb)
  }
}

// usage example
// first arg is fibonacci number, 1-based
fibonacci(3, function(res) { console.log('fibonacci number is ', res) })
```

**Comment by glenjamin** [comment]
Thats excellent! (although fewer dependencies isn't necessarily a goal of mine, NIH and all that :) )

Counting upwards and keeping track of n means you can also only call nextTick every x iterations, which should improve things as well. The outer function closes over the callback so I don't think you need to pass it through all the time. I'm unsure whether the closure or the passing would be "better" as far as memory usage and speed are concerned.

I'll definitely have a play with this tomorrow.

**Comment by glenjamin** [comment]
Incorporated this algorithm into the above commit. Thanks for the suggestion!
